package br.unifei.imc.EstadoDoSolo;

public enum TiposEstadoDoSolo {

/*Ideal->*/ UMIDO_NEUTRO_FERTIL,

/*Seco->*/ SECO_BASE_INFERTIL , SECO_NEUTRO_INFERTIL , SECO_ACIDO_INFERTIL , SECO_BASE_FERTIL , SECO_NEUTRO_FERTIL , SECO_ACIDO_FERTIL,

/*Umido->*/ UMIDO_BASE_INFERTIL , UMIDO_NEUTRO_INFERTIL , UMIDO_ACIDO_INFERTIL , UMIDO_BASE_FERTIL , UMIDO_ACIDO_FERTIL,

/*encharcado->*/ ENCHARCADO_BASE_INFERTIL , ENCHARCADO_NEUTRO_INFERTIL , ENCHARCADO_ACIDO_INFERTIL , ENCHARCADO_BASE_FERTIL , ENCHARCADO_NEUTRO_FERTIL , ENCHARCADO_ACIDO_FERTIL,

}
